# Generated by Django 4.0 on 2022-12-13 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField(null=True)),
                ('quantity', models.IntegerField(default=0)),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='db.fish')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('statusID', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('Hp', models.IntegerField()),
                ('Mp', models.IntegerField()),
                ('Str', models.IntegerField()),
                ('Dex', models.IntegerField()),
                ('Con', models.IntegerField()),
                ('Attk', models.IntegerField()),
                ('Def', models.IntegerField()),
                ('Hit', models.IntegerField()),
                ('Dodge', models.IntegerField()),
                ('Block', models.IntegerField()),
                ('Critical', models.IntegerField()),
                ('Agility', models.IntegerField()),
                ('Speed', models.IntegerField()),
                ('Friendly', models.IntegerField()),
                ('buffID', models.IntegerField()),
                ('debuffID', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PlayerCharacter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statusID', models.CharField(default=1, max_length=45)),
                ('jobID', models.CharField(default=1, max_length=45)),
                ('level', models.IntegerField(default=1)),
                ('exp', models.IntegerField(default=0)),
                ('title', models.CharField(default=1, max_length=45)),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player.inventory')),
            ],
        ),
    ]
