# Generated by Django 4.1.1 on 2023-01-09 14:59

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('system', '0001_initial'),
        ('db', '0002_alter_itemtype_options_alter_item_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='레벨 (1~100)')),
                ('exp', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000000)], verbose_name='경험치 (0~1000000)')),
                ('x', models.IntegerField(default=0, verbose_name='X 좌표 위치')),
                ('y', models.IntegerField(default=0, verbose_name='Y 좌표 위치')),
                ('z', models.IntegerField(default=0, verbose_name='Z 순서')),
                ('map', models.ForeignKey(default='중앙 광장', null=True, on_delete=django.db.models.deletion.SET_NULL, to='system.map', to_field='name', verbose_name='현재 맵')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='사용자 이름')),
            ],
            options={
                'verbose_name': '캐릭터',
                'verbose_name_plural': '캐릭터',
            },
        ),
        migrations.CreateModel(
            name='ItemStored',
            fields=[
                ('ItemStoredID', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('character', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='player.character', verbose_name='가방 소유자')),
                ('capacity', models.IntegerField(default=25, verbose_name='가방 용량')),
                ('usage', models.IntegerField(default=0, verbose_name='현재 사용량')),
                ('money', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': '가방',
                'verbose_name_plural': '가방',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('character', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='player.character', verbose_name='사용자 이름')),
                ('hp', models.IntegerField(default=100, verbose_name='체력')),
                ('mp', models.IntegerField(default=0, verbose_name='마나')),
                ('Str', models.IntegerField(default=0)),
                ('Dex', models.IntegerField(default=0)),
                ('Con', models.IntegerField(default=0)),
                ('Attk', models.IntegerField(default=0)),
                ('Def', models.IntegerField(default=0)),
                ('Hit', models.IntegerField(default=0)),
                ('Dodge', models.IntegerField(default=0)),
                ('Block', models.IntegerField(default=0)),
                ('Critical', models.IntegerField(default=0)),
                ('Agility', models.IntegerField(default=0)),
                ('Speed', models.IntegerField(default=0)),
                ('Friendly', models.IntegerField(default=0)),
                ('buffID', models.IntegerField(default=0)),
                ('debuffID', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': '상태',
                'verbose_name_plural': '상태',
            },
        ),
        migrations.CreateModel(
            name='ItemAmount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_amount', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(999)], verbose_name='수량 (1~999)')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item_belonging_to', to='db.item', verbose_name='아이템')),
                ('inventory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory_of', to='player.inventory', verbose_name='소유자')),
            ],
        ),
        migrations.AddField(
            model_name='inventory',
            name='items',
            field=models.ManyToManyField(blank=True, related_name='items_belonging_to', through='player.ItemAmount', to='db.item', verbose_name='보유 아이템'),
        ),
    ]
