# Generated by Django 4.1.1 on 2023-01-02 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='playercharacter',
            name='location',
            field=models.CharField(default='default_location', max_length=255),
        ),
    ]
