# Generated by Django 4.0 on 2022-12-05 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventory',
            old_name='PlayerCharacter',
            new_name='playerCharacter',
        ),
        migrations.RenameField(
            model_name='playercharacter',
            old_name='Account',
            new_name='account',
        ),
    ]
