# Generated by Django 4.1.1 on 2023-01-09 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0009_map_darkmodeyn_alter_map_height_alter_map_image_path_and_more'),
        ('player', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='location',
        ),
        migrations.AddField(
            model_name='character',
            name='map',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='system.map', verbose_name='현재 맵'),
        ),
        migrations.AddField(
            model_name='character',
            name='x',
            field=models.IntegerField(default=0, verbose_name='X 좌표 위치'),
        ),
        migrations.AddField(
            model_name='character',
            name='y',
            field=models.IntegerField(default=0, verbose_name='Y 좌표 위치'),
        ),
        migrations.AddField(
            model_name='character',
            name='z',
            field=models.IntegerField(default=0, verbose_name='Z 순서'),
        ),
    ]
