# Generated by Django 4.1.1 on 2023-01-03 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='location',
            field=models.CharField(default='location', max_length=255),
        ),
        migrations.AddField(
            model_name='inventory',
            name='money',
            field=models.IntegerField(default=0),
        ),
    ]
