# Generated by Django 4.1.1 on 2023-01-02 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventory',
            old_name='playerCharacter',
            new_name='PlayerCharacterID',
        ),
        migrations.RemoveField(
            model_name='status',
            name='statusID',
        ),
        migrations.AddField(
            model_name='inventory',
            name='money',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playercharacter',
            name='location',
            field=models.CharField(default='location', max_length=255),
        ),
        migrations.AddField(
            model_name='status',
            name='PlayerCharacterID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='player.playercharacter'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='status',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
