# Generated by Django 4.0 on 2022-12-06 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0002_rename_playercharacter_inventory_playercharacter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='weight',
            field=models.IntegerField(null=True),
        ),
    ]
