# Generated by Django 4.1.1 on 2023-01-02 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0002_playercharacter_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='money',
            field=models.IntegerField(default=0),
        ),
    ]
