# Generated by Django 4.0 on 2022-12-06 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0003_alter_inventory_quantity_alter_inventory_weight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='playerCharacter',
        ),
        migrations.AddField(
            model_name='playercharacter',
            name='inventory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='player.inventory'),
            preserve_default=False,
        ),
    ]
