# Generated by Django 4.1.1 on 2023-01-04 05:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0003_alter_itemamount_item_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='exp',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000000)], verbose_name='경험치 (0~1000000)'),
        ),
        migrations.AlterField(
            model_name='character',
            name='level',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='레벨 (1~100)'),
        ),
    ]
