# Generated by Django 4.1.1 on 2022-10-17 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=255)),
                ('userName', models.CharField(max_length=255)),
                ('Age', models.SmallIntegerField()),
                ('emailAddress', models.EmailField(max_length=30)),
            ],
        ),
    ]
