# Generated by Django 4.1.1 on 2022-10-18 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_user_age_user_birthday'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='userGender',
            field=models.CharField(choices=[(None, '성별 선택'), ('Men', '남성'), ('Women', '여성')], default='성별 선택', max_length=10),
        ),
    ]
