# Generated by Django 4.1.1 on 2023-01-09 14:59

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bgm',
            fields=[
                ('bgmID', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('bgmName', models.CharField(max_length=45)),
                ('bgmType', models.CharField(max_length=45)),
                ('bgmPath', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Date',
            fields=[
                ('dateID', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('dateEffect', models.CharField(max_length=45)),
                ('darkModeYn', models.CharField(max_length=45)),
                ('holidayYn', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Garnish',
            fields=[
                ('name', models.CharField(max_length=16, primary_key=True, serialize=False, verbose_name='이름')),
                ('description', models.CharField(blank=True, max_length=64, verbose_name='설명')),
                ('image_path', models.CharField(blank=True, max_length=200, null=True, verbose_name='이미지 경로')),
            ],
            options={
                'verbose_name': '맵 장식물',
                'verbose_name_plural': '맵 장식물',
            },
        ),
        migrations.CreateModel(
            name='GarnishArrangement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField(default=0, verbose_name='X 좌표 위치')),
                ('y', models.IntegerField(default=0, verbose_name='Y 좌표 위치')),
                ('z', models.IntegerField(default=0, verbose_name='Z 순서')),
                ('garnish', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='garnish', to='system.garnish', verbose_name='장식물')),
            ],
        ),
        migrations.CreateModel(
            name='Maptype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, verbose_name='분류 명')),
                ('description', models.CharField(blank=True, max_length=64, verbose_name='설명')),
            ],
            options={
                'verbose_name': '맵 종류',
                'verbose_name_plural': '맵 종류',
            },
        ),
        migrations.CreateModel(
            name='System',
            fields=[
                ('sysID', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('dateID', models.CharField(max_length=45)),
                ('weatherID', models.CharField(max_length=45)),
                ('timerID', models.CharField(max_length=45)),
                ('bgmID', models.CharField(max_length=45)),
                ('mapID', models.CharField(max_length=45)),
                ('auth', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Timer',
            fields=[
                ('timerID', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('timerName', models.CharField(max_length=45)),
                ('timerType', models.CharField(max_length=45)),
                ('timerSec', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('weatherID', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('weatherName', models.CharField(max_length=45)),
                ('weatherType', models.CharField(max_length=45)),
                ('weatherEffect', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='이름')),
                ('description', models.CharField(blank=True, max_length=64, verbose_name='설명')),
                ('required_level', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='진입 요구 레벨 (1~100)')),
                ('image_path', models.CharField(blank=True, max_length=200, null=True, verbose_name='이미지 경로')),
                ('width', models.IntegerField(default=100, validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(1000)], verbose_name='너비')),
                ('height', models.IntegerField(default=100, validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(1000)], verbose_name='높이')),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('coordinate', models.CharField(blank=True, max_length=255, null=True, verbose_name='좌표')),
                ('darkmodeYn', models.IntegerField(blank=True, null=True)),
                ('street', models.CharField(blank=True, max_length=255, null=True)),
                ('east_map', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='east_map_of', to='system.map', verbose_name='동쪽으로 향하는 맵')),
                ('garnishes', models.ManyToManyField(blank=True, through='system.GarnishArrangement', to='system.garnish', verbose_name='장식물 배치')),
                ('north_map', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='north_map_of', to='system.map', verbose_name='북쪽으로 향하는 맵')),
                ('south_map', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='south_map_of', to='system.map', verbose_name='남쪽으로 향하는 맵')),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='system.maptype', verbose_name='종류')),
                ('west_map', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='west_map_of', to='system.map', verbose_name='서쪽으로 향하는 맵')),
            ],
            options={
                'verbose_name': '맵',
                'verbose_name_plural': '맵',
            },
        ),
        migrations.AddField(
            model_name='garnisharrangement',
            name='map',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='map', to='system.map', verbose_name='맵'),
        ),
    ]
