# Generated by Django 4.0 on 2022-12-13 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bgm',
            fields=[
                ('bgmID', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('bgmName', models.CharField(max_length=45)),
                ('bgmType', models.CharField(max_length=45)),
                ('bgmPath', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Date',
            fields=[
                ('dateID', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('dateEffect', models.CharField(max_length=45)),
                ('darkModeYn', models.CharField(max_length=45)),
                ('holidayYn', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Map',
            fields=[
                ('mapID', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('mapName', models.CharField(max_length=45)),
                ('mapImgPath', models.CharField(max_length=45)),
                ('mapMenu', models.CharField(max_length=45)),
                ('darkModeYn', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='System',
            fields=[
                ('sysID', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('dateID', models.CharField(max_length=45)),
                ('weatherID', models.CharField(max_length=45)),
                ('timerID', models.CharField(max_length=45)),
                ('bgmID', models.CharField(max_length=45)),
                ('mapID', models.CharField(max_length=45)),
                ('auth', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Timer',
            fields=[
                ('timerID', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('timerName', models.CharField(max_length=45)),
                ('timerType', models.CharField(max_length=45)),
                ('timerSec', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('weatherID', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('weatherName', models.CharField(max_length=45)),
                ('weatherType', models.CharField(max_length=45)),
                ('weatherEffect', models.CharField(max_length=45)),
            ],
        ),
    ]
