# Generated by Django 4.1.1 on 2023-01-04 05:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='map',
            options={'verbose_name': '맵', 'verbose_name_plural': '맵'},
        ),
        migrations.RemoveField(
            model_name='map',
            name='location',
        ),
        migrations.RemoveField(
            model_name='map',
            name='mapID',
        ),
        migrations.AddField(
            model_name='map',
            name='description',
            field=models.CharField(blank=True, max_length=64, verbose_name='설명'),
        ),
        migrations.AddField(
            model_name='map',
            name='name',
            field=models.CharField(max_length=32, null=True, verbose_name='이름'),
        ),
        migrations.AlterField(
            model_name='map',
            name='coordinate',
            field=models.CharField(max_length=255, verbose_name='좌표'),
        ),
        migrations.AlterField(
            model_name='map',
            name='required_level',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='진입 요구 레벨 (1~100)'),
        ),
    ]
