# Generated by Django 4.1.1 on 2023-01-08 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='image_path',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='맵 이미지 경로'),
        ),
    ]
