# Generated by Django 4.1.1 on 2023-01-04 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_alter_map_options_remove_map_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
