# Generated by Django 4.1.1 on 2023-01-08 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_map_image_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maptype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, verbose_name='분류 명')),
                ('description', models.CharField(blank=True, max_length=64, verbose_name='설명')),
            ],
            options={
                'verbose_name': '맵 종류',
                'verbose_name_plural': '맵 종류',
            },
        ),
        migrations.AddField(
            model_name='map',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='system.maptype', verbose_name='아이템 종류'),
        ),
    ]
