# Generated by Django 4.1.1 on 2023-01-08 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_maptype_map_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Garnish',
            fields=[
                ('name', models.CharField(max_length=16, primary_key=True, serialize=False, verbose_name='이름')),
                ('description', models.CharField(blank=True, max_length=64, verbose_name='설명')),
                ('image_path', models.CharField(blank=True, max_length=200, null=True, verbose_name='이미지 경로')),
            ],
            options={
                'verbose_name': '맵 장식물',
                'verbose_name_plural': '맵 장식물',
            },
        ),
        migrations.AlterField(
            model_name='map',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='system.maptype', verbose_name='맵 종류'),
        ),
        migrations.CreateModel(
            name='GarnishArrangement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('garnish', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='garnish', to='system.garnish', verbose_name='장식물')),
                ('map', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='map', to='system.map', verbose_name='맵')),
            ],
        ),
        migrations.AddField(
            model_name='map',
            name='garnishes',
            field=models.ManyToManyField(blank=True, through='system.GarnishArrangement', to='system.garnish', verbose_name='장식물 배치'),
        ),
    ]
