# Generated by Django 4.1.1 on 2023-01-08 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0004_garnish_alter_map_type_garnisharrangement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='garnisharrangement',
            name='x',
            field=models.IntegerField(default=0, verbose_name='X 좌표 위치'),
        ),
        migrations.AddField(
            model_name='garnisharrangement',
            name='y',
            field=models.IntegerField(default=0, verbose_name='Y 좌표 위치'),
        ),
    ]
