# Generated by Django 4.1.1 on 2023-01-08 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0005_garnisharrangement_x_garnisharrangement_y'),
    ]

    operations = [
        migrations.AddField(
            model_name='garnisharrangement',
            name='z',
            field=models.IntegerField(default=0, verbose_name='Z 순서'),
        ),
    ]
