# Generated by Django 4.1.1 on 2023-01-09 05:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0006_garnisharrangement_z'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='east_map',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='east_map_of', to='system.map', verbose_name='동쪽 맵'),
        ),
        migrations.AddField(
            model_name='map',
            name='north_map',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='north_map_of', to='system.map', verbose_name='북쪽 맵'),
        ),
        migrations.AddField(
            model_name='map',
            name='south_map',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='south_map_of', to='system.map', verbose_name='남쪽 맵'),
        ),
        migrations.AddField(
            model_name='map',
            name='west_map',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='west_map_of', to='system.map', verbose_name='서쪽 맵'),
        ),
    ]
