# Generated by Django 4.1.1 on 2023-01-09 10:56

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0008_map_height_map_width_alter_map_coordinate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='darkmodeYn',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='map',
            name='height',
            field=models.IntegerField(default=100, validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(1000)], verbose_name='높이'),
        ),
        migrations.AlterField(
            model_name='map',
            name='image_path',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='이미지 경로'),
        ),
        migrations.AlterField(
            model_name='map',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='system.maptype', verbose_name='종류'),
        ),
        migrations.AlterField(
            model_name='map',
            name='width',
            field=models.IntegerField(default=100, validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(1000)], verbose_name='너비'),
        ),
    ]
