# Generated by Django 4.1.1 on 2023-01-09 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0009_map_darkmodeyn_alter_map_height_alter_map_image_path_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='map',
            name='name',
            field=models.CharField(max_length=32, null=True, unique=True, verbose_name='이름'),
        ),
    ]
