# Generated by Django 4.0 on 2022-12-04 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buildingID', models.CharField(max_length=45)),
                ('buildingName', models.CharField(max_length=45)),
                ('mapID', models.CharField(max_length=45)),
                ('buildingImgPath', models.CharField(max_length=45)),
                ('darkModeYn', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemID', models.CharField(max_length=45)),
                ('itemName', models.CharField(max_length=45)),
                ('itemEffect', models.CharField(max_length=45)),
                ('itemDescription', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobID', models.CharField(max_length=45)),
                ('jobName', models.CharField(max_length=45)),
                ('jobEffect', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='NoneActingObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objectID', models.CharField(max_length=45)),
                ('objectName', models.CharField(max_length=45)),
                ('objectType', models.CharField(max_length=45)),
                ('objectEffect', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='NPC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('npcID', models.CharField(max_length=45)),
                ('npcName', models.CharField(max_length=45)),
                ('npcType', models.CharField(max_length=45)),
                ('npcImgPath', models.CharField(max_length=45)),
            ],
        ),
    ]
