# Generated by Django 4.1.1 on 2023-01-08 15:37

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fishName', models.CharField(max_length=255)),
                ('selling_value', models.IntegerField()),
                ('buying_value', models.IntegerField()),
                ('exp', models.IntegerField()),
                ('location', models.CharField(max_length=255)),
                ('catchRate', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ItemInfo',
            fields=[
                ('itemID', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('itemName', models.CharField(max_length=45)),
                ('itemType', models.CharField(max_length=45)),
                ('sellingValue', models.IntegerField(default=0)),
                ('buyingValue', models.IntegerField(default=0)),
                ('exp', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Itemtype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, verbose_name='타입명')),
                ('description', models.CharField(blank=True, max_length=64, verbose_name='설명')),
            ],
            options={
                'verbose_name': '아이템 타입',
                'verbose_name_plural': '아이템 타입',
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('name', models.CharField(max_length=16, primary_key=True, serialize=False, verbose_name='직업')),
                ('description', models.CharField(blank=True, max_length=64, verbose_name='설명')),
            ],
            options={
                'verbose_name': '직업',
                'verbose_name_plural': '직업',
            },
        ),
        migrations.CreateModel(
            name='NoneActingObject',
            fields=[
                ('objectID', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('objectName', models.CharField(max_length=45)),
                ('objectType', models.CharField(max_length=45)),
                ('objectEffect', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='NPC',
            fields=[
                ('npcID', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('npcName', models.CharField(max_length=45)),
                ('npcType', models.CharField(max_length=45)),
                ('npcImgPath', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Script',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, null=True, unique=True, verbose_name='제목')),
            ],
            options={
                'verbose_name': '대본',
                'verbose_name_plural': '대본',
            },
        ),
        migrations.CreateModel(
            name='Seed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seedName', models.CharField(max_length=255, unique=True)),
                ('relatedItemID', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, unique=True, verbose_name='스킬명')),
                ('description', models.CharField(blank=True, max_length=64, verbose_name='설명')),
                ('hp_consumption', models.IntegerField(default=0, verbose_name='체력 소비량')),
                ('mp_consumption', models.IntegerField(default=0, verbose_name='마나 소비량')),
                ('cooldown_time', models.IntegerField(default=1000, verbose_name='재사용 대기시간(ms)')),
                ('activation_time', models.IntegerField(default=500, verbose_name='시연시간(ms)')),
                ('effect', models.CharField(blank=True, max_length=16, verbose_name='스킬효과')),
            ],
            options={
                'verbose_name': '스킬',
                'verbose_name_plural': '스킬',
            },
        ),
        migrations.CreateModel(
            name='Sentence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speaker', models.CharField(blank=True, max_length=32, null=True, verbose_name='화자')),
                ('text', models.TextField(blank=True, null=True, verbose_name='대사')),
                ('order', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='대화 순서')),
                ('captioning_elapsed_time', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(60000)], verbose_name='캡셔닝 지속시간 (ms) (0~60000)')),
                ('scripts', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='db.script')),
            ],
            options={
                'verbose_name': '문장',
                'verbose_name_plural': '문장',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, unique=True, verbose_name='아이템명')),
                ('description', models.CharField(blank=True, max_length=64, verbose_name='설명')),
                ('purchase_price', models.IntegerField(default=0, verbose_name='구입 가격 (냥)')),
                ('sell_price', models.IntegerField(default=0, verbose_name='판매 가격 (냥)')),
                ('weight', models.DecimalField(decimal_places=0, default=1, max_digits=6, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100000)], verbose_name='무게 (근)')),
                ('image_path', models.CharField(blank=True, max_length=200, null=True, verbose_name='이미지 경로')),
                ('hp', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='체력 (%)')),
                ('mp', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='마나 (%)')),
                ('power', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='힘 (%)')),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='db.itemtype', verbose_name='아이템 타입')),
            ],
            options={
                'verbose_name': '아이템',
                'verbose_name_plural': '아이템',
            },
        ),
        migrations.CreateModel(
            name='Dialogue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mainCategory', models.CharField(max_length=255)),
                ('middleCategory', models.CharField(max_length=255)),
                ('subCategory', models.CharField(max_length=255)),
                ('questMode', models.BooleanField()),
                ('scene', models.CharField(max_length=255)),
                ('dialogue', models.TextField()),
                ('npc', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='db.npc')),
            ],
        ),
        migrations.CreateModel(
            name='Building',
            fields=[
                ('name', models.CharField(max_length=32, primary_key=True, serialize=False, verbose_name='이름')),
                ('description', models.CharField(blank=True, max_length=64, verbose_name='설명')),
                ('image_path', models.CharField(blank=True, max_length=200, null=True, verbose_name='이미지 경로')),
                ('mapID', models.CharField(max_length=45)),
                ('darkModeYn', models.CharField(max_length=45)),
                ('sale_items', models.ManyToManyField(blank=True, to='db.item', verbose_name='판매 아이템')),
            ],
            options={
                'verbose_name': '건물',
                'verbose_name_plural': '건물',
            },
        ),
    ]
