# Generated by Django 4.0 on 2022-12-13 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('buildingID', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('buildingName', models.CharField(max_length=45)),
                ('mapID', models.CharField(max_length=45)),
                ('buildingImgPath', models.CharField(max_length=45)),
                ('darkModeYn', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Fish',
            fields=[
                ('fishID', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('fishName', models.CharField(max_length=45)),
                ('count', models.IntegerField(default=0)),
                ('sellingValue', models.IntegerField()),
                ('buyingValue', models.IntegerField()),
                ('exp', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('itemID', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('itemName', models.CharField(max_length=45)),
                ('itemEffect', models.CharField(max_length=45)),
                ('itemDescription', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('jobID', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('jobName', models.CharField(max_length=45)),
                ('jobEffect', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='NoneActingObject',
            fields=[
                ('objectID', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('objectName', models.CharField(max_length=45)),
                ('objectType', models.CharField(max_length=45)),
                ('objectEffect', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='NPC',
            fields=[
                ('npcID', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('npcName', models.CharField(max_length=45)),
                ('npcType', models.CharField(max_length=45)),
                ('npcImgPath', models.CharField(max_length=45)),
            ],
        ),
    ]
