# Generated by Django 4.1.1 on 2023-01-03 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fishName', models.CharField(max_length=255)),
                ('selling_value', models.IntegerField()),
                ('buying_value', models.IntegerField()),
                ('exp', models.IntegerField()),
                ('location', models.CharField(max_length=255)),
                ('catchRate', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Seed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seedName', models.CharField(max_length=255, unique=True)),
                ('relatedItemID', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='iteminfo',
            name='count',
        ),
    ]
