# Generated by Django 4.0 on 2022-12-17 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0001_initial'),
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='inventory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='player.inventory'),
        ),
    ]
