# Generated by Django 4.0 on 2022-12-04 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='building',
            name='id',
        ),
        migrations.RemoveField(
            model_name='item',
            name='id',
        ),
        migrations.RemoveField(
            model_name='job',
            name='id',
        ),
        migrations.RemoveField(
            model_name='noneactingobject',
            name='id',
        ),
        migrations.RemoveField(
            model_name='npc',
            name='id',
        ),
        migrations.AlterField(
            model_name='building',
            name='buildingID',
            field=models.CharField(max_length=45, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='item',
            name='itemID',
            field=models.CharField(max_length=45, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='job',
            name='jobID',
            field=models.CharField(max_length=45, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='noneactingobject',
            name='objectID',
            field=models.CharField(max_length=45, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='npc',
            name='npcID',
            field=models.CharField(max_length=45, primary_key=True, serialize=False),
        ),
    ]
