# Generated by Django 4.1.1 on 2023-01-04 04:25

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_fish_seed_remove_iteminfo_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='durability',
            field=models.DecimalField(decimal_places=0, default=100, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='내구도 (%)'),
        ),
        migrations.AddField(
            model_name='item',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='db.itemtype', verbose_name='아이템 타입'),
        ),
        migrations.AlterField(
            model_name='item',
            name='purchase_price',
            field=models.IntegerField(default=0, verbose_name='구입 가격 (냥)'),
        ),
        migrations.AlterField(
            model_name='item',
            name='sell_price',
            field=models.IntegerField(default=0, verbose_name='판매 가격 (냥)'),
        ),
        migrations.AlterField(
            model_name='item',
            name='weight',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=6, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100000)], verbose_name='무게 (근)'),
        ),
    ]
