# Generated by Django 4.0 on 2022-12-17 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_item_inventory'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemInfo',
            fields=[
                ('itemID', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('itemName', models.CharField(max_length=45)),
                ('itemType', models.CharField(max_length=45)),
                ('sellingValue', models.IntegerField(default=0)),
                ('buyingValue', models.IntegerField(default=0)),
                ('exp', models.IntegerField(default=0)),
                ('count', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='Fish',
        ),
    ]
