# Generated by Django 4.0 on 2022-12-06 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_remove_building_id_remove_item_id_remove_job_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fishID', models.CharField(max_length=45)),
                ('fishName', models.CharField(max_length=45)),
                ('sellingValue', models.IntegerField()),
                ('buyingValue', models.IntegerField()),
                ('exp', models.IntegerField()),
            ],
        ),
    ]
