# Generated by Django 4.0 on 2022-12-06 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_fish'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fish',
            name='id',
        ),
        migrations.AlterField(
            model_name='fish',
            name='fishID',
            field=models.CharField(max_length=45, primary_key=True, serialize=False),
        ),
    ]
