# Generated by Django 4.0 on 2022-12-22 00:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_iteminfo_delete_fish'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dialogue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=45)),
                ('dialogue', models.TextField()),
                ('npc', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='db.npc')),
            ],
        ),
    ]
