# Generated by Django 4.1.1 on 2023-01-04 11:08

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_item_durability_item_type_alter_item_purchase_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Script',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, null=True, unique=True, verbose_name='제목')),
            ],
            options={
                'verbose_name': '대본',
                'verbose_name_plural': '대본',
            },
        ),
        migrations.CreateModel(
            name='Sentence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speaker', models.CharField(blank=True, max_length=32, null=True, verbose_name='화자')),
                ('text', models.TextField(blank=True, null=True, verbose_name='대사')),
                ('order', models.IntegerField(verbose_name='대화 순서')),
                ('captioning_elapsed_time', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(60000)], verbose_name='캡셔닝 지속시간 (ms) (0~60000)')),
                ('scripts', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='db.script')),
            ],
            options={
                'verbose_name': '문장',
                'verbose_name_plural': '문장',
            },
        ),
    ]
