# Generated by Django 4.0 on 2022-12-26 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0004_dialogue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dialogue',
            name='type',
        ),
        migrations.AddField(
            model_name='dialogue',
            name='mainCategory',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dialogue',
            name='middleCateogry',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dialogue',
            name='questMode',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dialogue',
            name='scene',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dialogue',
            name='subCateogry',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
