# Generated by Django 4.1.1 on 2023-01-02 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0007_rename_middlecateogory_dialogue_middlecategory_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fishName', models.CharField(max_length=255)),
                ('selling_value', models.IntegerField()),
                ('buying_value', models.IntegerField()),
                ('exp', models.IntegerField()),
                ('location', models.CharField(max_length=255)),
                ('catchRate', models.IntegerField()),
            ],
        ),
    ]
