# Generated by Django 4.1.1 on 2023-01-03 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0009_remove_iteminfo_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seedName', models.CharField(max_length=255)),
                ('itemID', models.CharField(max_length=255)),
            ],
        ),
    ]
