# Generated by Django 4.1.1 on 2023-01-03 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0010_seed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seed',
            old_name='itemID',
            new_name='relatedItemID',
        ),
    ]
