# Generated by Django 4.0 on 2022-12-05 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_rename_id_account_accountid_account_playerid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='id',
            field=models.CharField(default='', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='accountID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='account',
            name='playerID',
            field=models.CharField(max_length=45),
        ),
    ]
