# Generated by Django 4.0 on 2022-12-05 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_account_id_alter_account_accountid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='id',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='playerID',
            field=models.CharField(max_length=45, null=True),
        ),
    ]
